### ISSUE TITLE
The date picker does not scale appropriately for users on PC/Laptop

### ISSUE THREAD

**Issue by HakeemAlavi** [adala-wanyande/afya-one#1]
It goes off screen making it unusable with a mouse/trackpad forcing the user to rely solely on their keyboard

**Comment by adala-wanyande** [comment]
![2024-03-16](https://github.com/adala-wanyande/afya-one/assets/118197541/d22dfc37-ac56-4162-9760-57ac4f0f44eb)
Fixed
