### ISSUE TITLE
Password Reset Feature

### ISSUE THREAD

**Issue by HakeemAlavi** [adala-wanyande/afya-one#6]
There are no password reset options that the user may utilize in case they forget their current password. This leaves them with a few options for using the web application:
1. Creating a new account in order to access the web application
2. Randomly guess possible passwords until one works
3. Give up and stop using the web application altogether

As shown above, all the alternatives are flawed, and the password reset feature is needed, as soon as possible

**Comment by adala-wanyande** [comment]
This has been addressed in this [commit](https://github.com/adala-wanyande/afya-one/commit/7f22fed3b3303ba2d3590b5aabe9776dceb0170e)🤓 Have a great day Hakeem!
